### ISSUE TITLE
Missing required config value at 'integrations.bitbucketServer[0].host'

### ISSUE THREAD

**Issue by cmoulliard** [ch007m/my-janus#1]
## Issue

When we install janus/backstage as documented in the [README.md](https://github.com/ch007m/my-janus#how-to) of this project, the backstage pod reports this error:
```
Loaded config from app-config.yaml, env
2023-09-29T10:01:02.938Z backstage info Found 2 new secrets in config that will be redacted
Backend failed to start up Error: Missing required config value at 'integrations.bitbucketServer[0].host'
    at ConfigReader.getString (/opt/app-root/src/node_modules/@backstage/config/dist/index.cjs.js:240:13)
    at readBitbucketServerIntegrationConfig (/opt/app-root/src/node_modules/@backstage/integration/dist/index.cjs.js:818:23)
    at Array.map (<anonymous>)
    at readBitbucketServerIntegrationConfigs (/opt/app-root/src/node_modules/@backstage/integration/dist/index.cjs.js:842:18)
    at _BitbucketServerIntegration.factory (/opt/app-root/src/node_modules/@backstage/integration/dist/index.cjs.js:884:19)
    at ScmIntegrations.fromConfig (/opt/app-root/src/node_modules/@backstage/integration/dist/index.cjs.js:1902:51)
    at /opt/app-root/src/node_modules/@backstage/backend-common/dist/index.cjs.js:1387:52
    at UrlReaders.create (/opt/app-root/src/node_modules/@backstage/backend-common/dist/index.cjs.js:3802:22)
    at UrlReaders.default (/opt/app-root/src/node_modules/@backstage/backend-common/dist/index.cjs.js:3817:23)
    at makeCreateEnv (/opt/app-root/src/packages/backend/dist/index.cjs.js:482:50)
    at main (/opt/app-root/src/packages/backend/dist/index.cjs.js:541:21)
Stream closed EOF for idp/janus-idp-backstage-5dfcd4b59-2825h (backstage-backend)
```

**Comment by cmoulliard** [comment]
To fix this error, a backstage `app-config.yaml` file including:
```
integrations:
  bitbucketServer:
    - host: bitbucket.com
      apiBaseUrl: temp
      username: temp
      password: temp
```
must be created and mounted as configMap. It is also needed to specify to the backstage Helm chart that a file containing the app-config.yaml must be created from a configMapReference
```
## Helm values
backstage:
...
  extraAppConfig:
    - filename: app-config.yaml
      configMapRef: app-config
```
You can then issue such commands to create the configmap and rollout:
```
kubectl delete configmap app-config -n idp
kubectl create configmap app-config -n idp \
  --from-file=app-config.yaml=$(pwd)/app-config.yaml
  
kubectl rollout restart deployment/janus-idp-backstage -n idp
```
